sudo: required
services: docker
language: java
install: skip
before_script:
  - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin registry.hub.docker.com
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - docker images
  - docker push registry.hub.docker.com/pinkyo/jre-8