sudo: required
services: docker
language: java
install: skip
before_script:
  - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - mvn deploy -DskipTests=true -Dmaven.javadoc.skip=true -B -V
